### ISSUE TITLE
Wrong price for fWETH?

### ISSUE THREAD

**Issue by bZxFan** [bZxNetwork/fulcrum_ui#193]
It looks like the price of fWETH is wrong when you go to margin long/short it. 

1. Go to margin long fWETH on the Fulcrum Trade interface
2. Click on "buy"
3. The price is showing something else. 

**Screenshots**
![image](https://user-images.githubusercontent.com/69940522/90697996-ec624600-e23c-11ea-813f-dcb3c5d3b683.png)

**Comment by tomcbean** [comment]
Hello. The prices on Kovan don't necessarily reflect mainnet. fWETH is a simulated asset.

**Comment by tomcbean** [comment]
Closing since Kovan accurately reflects the prices that the pricefeeds give there.
