### ISSUE TITLE
Charting timeframes greater than 12 hours doesn't work.

### ISSUE THREAD

**Issue by bZxFan** [bZxNetwork/fulcrum_ui#196]
For all timeframes above 12 hours, it fails to render. If I go to inspect (in Chrome), I notice there's an unending amount of XHRs. Infinite loop?

If I look at them, this is the response 
`{"error":true,"reason":"server_error","additional_data":"unconfigured table ticker_table_1d"}`

Notice `unconfigured table ticker_table_1d` includes the timeframe.

**Comment by Kharabet** [comment]
Fixed here https://github.com/bZxNetwork/fulcrum_ui/pull/222/commits/2642d3ec33ab8f109af9c02551cb640332727c77
