### ISSUE TITLE
Backspace key doesn't work for new borrow (Torque Loans)

### ISSUE THREAD

**Issue by acedabook** [bZxNetwork/fulcrum_ui#197]
**Describe the bug**
I attempted to create a new USDT loan using Kovan fWETH and entered a number, attempted to delete the number with 'backspace' or highlight and 'delete,' but it wouldn't erase to a blank slate.

**To Reproduce**
1. Go to 'https://kovan.torque.loans/borrow'
2. Click on 'USDT'
3. Enter any digit, eg '3'
4. Attempt to delete or backspace and you cannot change or remove the number

**Expected behavior**
Clear the number to allow the user to start fresh instead of closing the screen and starting again

**Desktop (please complete the following information):**
 - Mac OS
 - Browser Chrome
 - Version 84.0.4147.125

**Comment by OlehX** [comment]
#225
