### ISSUE TITLE
Request: Keep repayment percentage highlighted after selecting - Torque

### ISSUE THREAD

**Issue by iwearahoodie** [bZxNetwork/fulcrum_ui#199]
**Is your feature request related to a problem? Please describe.**
When selecting 25% or 50% or whatever it would be good if the percentage stayed highlighted after clicking on it. The number has a blue outline when I mouse over it, but when moving the mouse away, it disappears. This makes me second guess whether I have actually selected the amount I meant to, and involves me then clicking another number, then clicking back to the original one I meant to. 

**Describe the solution you'd like**
Whatever is selected remains highlighted. 

**Describe alternatives you've considered**
I have considered nothing else. 

**Additional context**

<img width="904" alt="Screen Shot 2020-08-22 at 1 53 50 pm" src="https://user-images.githubusercontent.com/58599201/90949857-e9ef2e80-e47e-11ea-934d-ac477c823512.png">

**Comment by Kharabet** [comment]
Fixed here https://github.com/bZxNetwork/fulcrum_ui/pull/222/commits/a76b8233e0a39730f02d33a6377f4ef246a59dd0 (at PR #222)

**Comment by Kharabet** [comment]
Not it looks like at the screenshot
![image](https://user-images.githubusercontent.com/14793248/91589088-d56cd380-e961-11ea-8de5-279f64b7051f.png)
