### ISSUE TITLE
Torque loans asset cuts down into footer on borrow page [Chrome 78.0.3904.108]

### ISSUE THREAD

**Issue by KadenZipfel** [bZxNetwork/fulcrum_ui#20]
![image](https://user-images.githubusercontent.com/30579067/69566263-8ecdf100-0f6b-11ea-80e9-5b107889fcb7.png)

I can fix this in a PR if wanted.

**Comment by tomcbean** [comment]
Good catch! Feel free to commit a fix to this for this PR. Thanks!

**Comment by tomcbean** [comment]
We went ahead and fixed this. Thanks.
