### ISSUE TITLE
Request - change default text while wallet is loading in Torque dashboard

### ISSUE THREAD

**Issue by iwearahoodie** [bZxNetwork/fulcrum_ui#202]
**Is your feature request related to a problem? Please describe.**
While metamask etc is loading, the default text displayed is "Looks like you do not have any loans"
Once the wallet does load, the loans eventually appear. 

**Describe the solution you'd like**
Have a message stating that wallet is loading or needs to be loaded in order to display loans, or something to that effect. 

**Describe alternatives you've considered**
Or no message at all and instead a loading animation...  

**Screenshot**

<img width="1437" alt="Screen Shot 2020-08-22 at 3 20 06 pm" src="https://user-images.githubusercontent.com/58599201/90951205-48baa500-e48b-11ea-9192-1021ff4db44e.png">

**Comment by sneg55** [comment]
@Kharabet  can you please delete "lorem ipsum"

**Comment by Kharabet** [comment]
Fixed at #224
