### ISSUE TITLE
Transition between screens on Fulcrum should be smoother

### ISSUE THREAD

**Issue by trixiebits** [bZxNetwork/fulcrum_ui#206]
**Is your feature request related to a problem? Please describe.**
Sometimes when switching between the Lend and Trade screens on Fulcrum, there is a short pause/freeze. I presume it's trying to load something. 

This also happens to some extent when loading the screens for the first time (e.g. clicking a URL to Fulcrum's Lend page). The page seems to have loaded but the cursor doesn't turn into a hand when it is over a Lend button.

**Describe the solution you'd like**
Dim some part of the screen so that it is clear to the user that the next screen is loading. Or an hourglass / beachball somewhere to serve the same purpose.

**Describe alternatives you've considered**
N/A

**Additional context**
This seems to happen more when a wallet is not connected. I usually connect a wallet only when I want to trade.

**Comment by sneg55** [comment]
This would be addressed with a transition to thegraph instead of pulling data from web3 directly.
