### ISSUE TITLE
Request - Fulcrum - need a way to easily return to chart view

### ISSUE THREAD

**Issue by iwearahoodie** [bZxNetwork/fulcrum_ui#207]
**Is your feature request related to a problem? Please describe.**
After clicking on "manage", there is no clear way to return to main view with charts. 
One has to click around for a bit before discovering that the way to return is to select a market from the drop down, or to refresh the page.  

**Describe the solution you'd like**
A button/link/option to return to main view other than opening the market selection drop down. 

**Describe alternatives you've considered**
Have a "markets" button appear only when manage has been selected. 

**Additional context**
<img width="1600" alt="Screen Shot 2020-08-22 at 7 34 00 pm" src="https://user-images.githubusercontent.com/58599201/90955238-6fd69e00-e4ae-11ea-81a4-1c802aed074a.png">

**Comment by AoDev** [comment]
Brought to [clubhouse](https://app.clubhouse.io/bzx1/story/711/feat-fulcrum-add-an-easy-way-to-go-back-to-chart)

**Comment by AoDev** [comment]
Improvements in #328
