### ISSUE TITLE
Torque loans dashboard shows placeholder text if I have no loans

### ISSUE THREAD

**Issue by aphasiac2002** [bZxNetwork/fulcrum_ui#211]
**Describe the bug**
Visting the Torque loans dashboard with no loans open shows the text "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups."

**To Reproduce**
1. Ensure you have no loans open.
2. Go to https://kovan.torque.loans/dashboard

**Expected behavior**
Don't show placeholder text

**Screenshots**
![image](https://user-images.githubusercontent.com/17522454/90969422-f92bb600-e52a-11ea-8bfe-ae5b42595aca.png)

**Desktop (please complete the following information):**
Windows 10, Chrome

**Comment by sneg55** [comment]
@Kharabet we need to delete "lorem ipsum"

**Comment by Kharabet** [comment]
Duplicate of #202
