### ISSUE TITLE
Torque - Borrow More window display error

### ISSUE THREAD

**Issue by RomanHiden** [bZxNetwork/fulcrum_ui#217]
**Describe the bug**

**To Reproduce**
1. Go to Torque -> Your Loans
2. Click on Borrow More
3. Enter arbitrary big amount
4. See error - Display Error

**Expected behavior**
More clear error of what happened and what "Display Error" mean

**Screenshots**
![image](https://user-images.githubusercontent.com/2690588/91231505-08cb1a80-e736-11ea-81ea-2e975cb600ac.png)

**Comment by OlehX** [comment]
#226
