### ISSUE TITLE
Problems with torque.loans calculating the wrong collateral required in the UI.

### ISSUE THREAD

**Issue by waiferthin** [bZxNetwork/fulcrum_ui#240]
**Describe the bug**
When you to go to torque.loans, depending on the numbers you enter into the UI, the collateral sometimes reads as 3.983696778153331e+57. 

**To Reproduce**
1. Go to [](https://torque.loans/)
2. In the default DAI to ETH collateral window, enter **2**. A normal amount appears in the collateral amount. 
3. Enter 3. The collateral changes to 3.983696778153331e+57.

The appearance of this number seems to be completely random. For example, 400 shows up as 1.46 ETH. 4000 shows up, again, as 3.983696778153331e+57

**Expected behavior**
It should be reading the proper collateral amounts.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome (Version 85.0.4183.83 (Official Build) (64-bit)) and Brave (Version 1.13.82 Chromium: 85.0.4183.83 (Official Build) (64-bit))

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aphasiac2002** [comment]
Ooops I missed this.

I have the same bug: https://github.com/bZxNetwork/fulcrum_ui/issues/253
