### ISSUE TITLE
Fulcrum lending dashboard doesn't show previously accumulated profit (interest)

### ISSUE THREAD

**Issue by piquiIIo** [bZxNetwork/fulcrum_ui#252]
**Describe the bug**
I am lending USDC at https://app.fulcrum.trade/lend. When I view the page, my "Profit" (total accumulated interest) is rising as I watch. However, if I refresh the website, the "Profit" field resets and starts counting from 0. This means it's impossible to see my current accumulated interest.

**To Reproduce**
1. Go to https://app.fulcrum.trade/lend
2. Lend some USDC
3. Watch the "Profit" field rise in real time, until it's some significant number (e,g. $1).
4. Refresh the webpage.
"Profit" starts counting again from 0.

**Expected behavior**
"Profit" field should always show current accumulated interest, and start counting upwards from there. In the above example, it should start at $1. Other lending sites such as Compound are able to do this.

**Comment by OlehX** [comment]
#262
