### ISSUE TITLE
Collateral ratios of each asset should displayed when taking our a loan

### ISSUE THREAD

**Issue by ChrisbZx** [bZxNetwork/fulcrum_ui#255]
For clarity when taking out a loan the rations and liquidation markdowns should be clearly displayed as in the following image.

![image](https://user-images.githubusercontent.com/70503269/92296318-d1027500-ef76-11ea-807e-13b55d30d471.png)

In addition to the % being shows the estimated values in the token/coin should also be displayed in each column

**Comment by AoDev** [comment]
This has been brought to [clubhouse](https://app.clubhouse.io/bzx1/story/696/feat-torque-add-more-contextual-info-for-the-users) as part of Torque improvements
