### ISSUE TITLE
Staked tokens continue to display after they have been moved from the wallet

### ISSUE THREAD

**Issue by ChrisbZx** [bZxNetwork/fulcrum_ui#256]
After tokens have been staked on the staking dashboard, the should disappear from the staked amount when the tokens leave the wallet. 

Currently when tokens leave the wallet they still remain staked on the UI even though they have stopped collecting rewards. 
This prevents users from being able to restake those tokens.

**Comment by piquiIIo** [comment]
Maybe related: https://github.com/bZxNetwork/fulcrum_ui/issues/261

**Comment by AoDev** [comment]
Closing this issue. It is happening because of the temporary staking contract. These problems will disappear once we release the staking module.
