### ISSUE TITLE
The calculator on the torque home page gives out incorrect figures

### ISSUE THREAD

**Issue by ChrisbZx** [bZxNetwork/fulcrum_ui#257]
The calculator up the top of torque.loans gives the same value as displayed in this image no matter what is entered.
![image](https://user-images.githubusercontent.com/70503269/92297214-445cb480-ef80-11ea-93db-efd4c8f7122e.png)

**Comment by aphasiac2002** [comment]
Same bug: https://github.com/bZxNetwork/fulcrum_ui/issues/253
