### ISSUE TITLE
Staking dashboard shows 2x staked balance

### ISSUE THREAD

**Issue by piquiIIo** [bZxNetwork/fulcrum_ui#261]
**Describe the bug**
I staked all my BZRX then lent out the same BZRX on Fulcrum

The staking dashboard now says I have 2x tokens and 2x rewards

**To Reproduce**
1. Go to https://staking.bzx.network/
2. Stake your whole BZRX balance
3. Go to https://app.fulcrum.trade/lend
4. Lend your whole BZRX balance
5. Go to https://staking.bzx.network 
and view staked tokens.

**Desktop (please complete the following information):**
 Windows 10, Chrome, Metamask

**Additional context**
I also have some vBZRX staked. Unsure if related.

**Comment by AoDev** [comment]
Closing this issue. It is happening because of the temporary staking contract. These problems will disappear once we release the staking module.
