### ISSUE TITLE
Making clear/customising fronted interest payments for positions

### ISSUE THREAD

**Issue by ChrisbZx** [bZxNetwork/fulcrum_ui#266]
Currently the interest payments automatically deducted from a margin loan is 28 days worth by default. 
In the high interest rate environment we currently have this ends up significantly detracting from users ability to margin trade, as their initial outlay is heavily cut into to front these payments. 

I would recommend making this extremely clear in the UI so to not confuse people about their position, as currently they just think they are being short changed as they can't see what's happening. 

In addition to this, allowing people to customise the amount of interest payments they put up initially (3 days worth for example instead of 28 days worth) would allow short term traders not to cut into their initial outlay as significantly as they currently do, as with the current rates it makes it impractical to trade.

**Comment by ChrisbZx** [comment]
In addition to this, it should be made clear what fronting interest actually does. 
Something as simple as:
"Fronting interest increases the amount of funds have set aside for interest payments upfront. This extends the amount of time your loan can survive without using your collateral to pay interest"

**Comment by AoDev** [comment]
Moved to [clubhouse](https://app.clubhouse.io/bzx1/story/707/making-clear-customising-fronted-interest-payments-for-positions)
