### ISSUE TITLE
Interest collected refreshes along with the page. Does not accrue properly

### ISSUE THREAD

**Issue by ChrisbZx** [bZxNetwork/fulcrum_ui#267]
When lending funds, interest does not track correctly. It resets with every refresh of the page. 

![giphy](https://user-images.githubusercontent.com/70503269/92430160-5ab07d80-f1d7-11ea-9de6-4cd5de3bfc12.gif)

**Comment by Kharabet** [comment]
Fixed at commit https://github.com/bZxNetwork/fulcrum_ui/commit/fd459fccdd54e21641d5c557134ee8879660e463
