### ISSUE TITLE
Balancer pool that can be used for staking should be linked

### ISSUE THREAD

**Issue by ChrisbZx** [bZxNetwork/fulcrum_ui#279]
We should link the specific balancer pool on the dashboard, perhaps here:

![image](https://user-images.githubusercontent.com/70503269/92712185-a9f3db00-f39c-11ea-9c13-8cb61bd3ae89.png)

This would make it easier for people to find

**Comment by AoDev** [comment]
@ChrisbZx . I have moved it to [clubhouse](https://app.clubhouse.io/bzx1/story/698/feat-staking-add-link-to-balancer-pool)
