### ISSUE TITLE
Link to contract ABIs goes to 404 page at fulcrum.trade website

### ISSUE THREAD

**Issue by Kharabet** [bZxNetwork/fulcrum_ui#84]
Link https://fulcrum.trade/artifacts has no page or redirect to another page at new https://fulcrum.trade/

This link was found at https://docs.bzx.network/fulcrum-integration/contract-abis

**Comment by sneg55** [comment]
@tomcbean  FYI, it's the same issue we talked before Denver. Need to move /artifacts to artifacts.fulcrum subdomain

**Comment by tomcbean** [comment]
artifacts.fulcrum.trade, artifacts.torque.loans, artifacts.bzx.network are all setup and point to the same place
