### ISSUE TITLE
Intercom widget is missing at app.fulcrum.trade

### ISSUE THREAD

**Issue by sneg55** [bZxNetwork/fulcrum_ui#95]
Intercom widget is missing at app.fulcrum.trade, need to figure out what is happening and restore it.

**Comment by sneg55** [comment]
@Kharabet

**Comment by Kharabet** [comment]
@sneg55 I suppose app.fulcrum.trade domain should be whitelisted explictly (intercom do not identify subdomains as a part of fulcrum.trade).

![image](https://user-images.githubusercontent.com/14793248/75661900-d81e9280-5c76-11ea-85ae-34872e539220.png)

**Comment by Kharabet** [comment]
Info from docs https://www.intercom.com/help/en/articles/4418-whitelisting-the-domains-you-use-with-intercom 

![image](https://user-images.githubusercontent.com/14793248/75662002-0c924e80-5c77-11ea-8960-4628301302fa.png)

**Comment by tomcbean** [comment]
This is resolved.
